name: "clean-values"
version: "v0.0.1-alpha.1"
command: "$HELM_PLUGIN_DIR/bin/helm-clean-values"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh '$HELM_PLUGIN_DIR'"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh '$HELM_PLUGIN_DIR'"